# Generated by Django 5.2.7 on 2025-10-09 16:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meddy_tourguides', '0004_alter_blogpost_image_alter_destination_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountedtour',
            name='image',
            field=models.FileField(upload_to='discounted_tours/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif', 'webp'])]),
        ),
    ]
