# Generated by Django 5.2.7 on 2025-10-24 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meddy_tourguides', '0006_accommodation_contactmessage_newslettersubscriber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
